name: Adam Pash
description: Writings about things
url: http://adampash.com
relative_permalinks: false
markdown: maruku
pygments: true

permalink: /:title

timezone: America/New_York

include: [feed]
